export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_DETAILS_SUCCESS = "GET_BLOGS_DETAILS_SUCCESS";
export const OPEN_BLOG = "OPEN_BLOG";
