export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";

export const OPEN_ARTICLES = "OPEN_ARTICLES";
