export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const INCREASE_BY_TWO_COUNTER = "INCREASE_BY_TWO_COUNTER";
export const MULTIPLY_COUNTER = "MULTIPLY_COUNTER";
export const DİVİDE_COUNTER = "DİVİDE_COUNTER";
export const MULTIPLY_VALUE = "MULTIPLY_VALUE";
